import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>My staking dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center">
          <section className="px-5 border rounded-lg my-20 shadow-lg bg-[#0000009d]">
            <h2 className="text-5xl text-center p-7">
              GM GM GM ! <br />
              🎆 Welcome to BUIDL Day-2 🎆
            </h2>
          </section>
        </div>
      </main>
    </>
  );
}
